### ISSUE TITLE
::before and ::after ?

### ISSUE THREAD

**Issue by paintparty** [AutoScreencast/codesunaba#2]
Great project!

Does Sunaba's current css implementation support `::before` and `::after` pseudoelements?

I could not get them to work ...

However, this worked as expected (with the included `hello-world-example.core`):
```
.header::first-letter{
  color:red;
}
```

**Comment by AutoScreencast** [comment]
Thanks @paintparty !

It turns out, I was unnecessarily escaping quotes in CSS, so any "" or '' in pseudo-elements' CSS (e.g. in the `content` property) did not work. I've fixed that in this [commit](https://github.com/AutoScreencast/codesunaba/commit/e6a9f2dce1b95dfeb8460321c5e8aafa95ca9c36).

I've tested it with the `::before` pseudo-element, with content property:

<img width="1067" alt="Screen Shot 2021-03-18 at 14 49 31" src="https://user-images.githubusercontent.com/53940669/111579335-2e666100-87f9-11eb-87ef-6b64d70927a0.png">

Please feel free to re-open this issue if you are still experiencing any problems.

**Comment by paintparty** [comment]
<img width="936" alt="Screen Shot 2021-03-18 at 10 14 23 AM" src="https://user-images.githubusercontent.com/1106506/111668306-dcaae000-87d2-11eb-8c57-720a10f051f2.png">
